### ISSUE TITLE
AutoCraft not recognizing third-party crafting recipes on load and needs to be reloaded to recognize them.

### ISSUE THREAD

**Issue by The-Nyla** [keksexception/AutoCraftNewMinecraft#4] opened 2022-11-19 16:47 UTC
On starting or restarting my server I noticed that AutoCraft only shows vanilla recipes, but once I use /autocraft reload, it correctly recognizes my custom recipes. I use the plugin "CustomCrafting" (https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-16-1-19-premium.95513/), for all my recipes, and I think the issue is probably that CustomCrafting is loading custom recipes after AutoCraft loads and checks for recipes. I'm not sure if this issue occurs with other recipe plugins, but it might if they load recipes after AutoCraft is enabled.

**Comment by keksexception** [comment] 2022-11-19 18:04
Hey, Thanks for your report! As you said, the issue is that CustomCrafting is registering custom recipes after AutoCraft is loading the recipes. To prevent this issue i will add an configurable delay for AutoCraft, that should solve the issue. It will be included in the next update.

**Comment by The-Nyla** [comment] 2022-11-19 18:10
Thanks!

**Closed as completed** 2022-11-20 11:40 UTC
Labels: solved
